Try to fix aarch64 cross-compile
We get "undefined reference to `__memmove_chk'" when compiling
pcre2 (via pcre2-sys) on newer Ubuntu.

I can't reproduce that on arch, so I'm assuming it's down to
_FORTIFY_SOURCE being set higher.